{% set name = "dash-bootstrap-components" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 30d48340d6dc89831d6c06e400cd4236f0d5363562c05b2a922f21545695a082

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - hatchling
    - dash >=2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - dash_bootstrap_components

about:
  home: https://dash-bootstrap-components.opensource.faculty.ai/
  license: MIT
  license_family: Apache
  license_file: LICENSE.txt
  summary: Bootstrap components for Plotly Dash

  description: |
    dash-bootstrap-components is a library of Bootstrap components for use with Plotly Dash,
    that makes it easier to build consistently styled Dash apps with complex, responsive layouts.
  doc_url: https://dash-bootstrap-components.opensource.faculty.ai/
  dev_url: https://github.com/facultyai/dash-bootstrap-components

extra:
  recipe-maintainers:
    - holtgrewe
    - pbugnion
    - tcbegley
