{% set name = "dash-bootstrap-components" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05c2e2767a8ab104fc950d15482d09dde59d21f1e9bd5809d30672e61b7f420c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - setuptools
    - dash >=2.0.0

test:
  imports:
    - dash_bootstrap_components

about:
  home: https://dash-bootstrap-components.opensource.faculty.ai/
  license: MIT
  license_family: Apache
  license_file: LICENSE.txt
  summary: Bootstrap components for Plotly Dash

  description: |
    dash-bootstrap-components is a library of Bootstrap components for use with Plotly Dash,
    that makes it easier to build consistently styled Dash apps with complex, responsive layouts.
  doc_url: https://dash-bootstrap-components.opensource.faculty.ai/
  dev_url: https://github.com/facultyai/dash-bootstrap-components

extra:
  recipe-maintainers:
    - holtgrewe
    - pbugnion
    - tcbegley
