# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: dash-bootstrap-components
  version: "2.0.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dash_bootstrap_components-${{ version }}.tar.gz
  sha256: c3206c0923774bbc6a6ddaa7822b8d9aa5326b0d3c1e7cd795cc975025fe2484

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - dash >=3.0.4

tests:
  - python:
      imports:
        - dash_bootstrap_components
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Bootstrap components for Plotly Dash
  homepage: https://dash-bootstrap-components.opensource.faculty.ai/
  description: |
    dash-bootstrap-components is a library of Bootstrap components for use with Plotly Dash,
    that makes it easier to build consistently styled Dash apps with complex, responsive layouts.
  documentation: https://www.dash-bootstrap-components.com/
  repository: https://github.com/dbc-team/dash-bootstrap-components/
  license: Apache-2.0
  license_file:
    - NOTICE.txt
    - LICENSE

extra:
  recipe-maintainers:
    - holtgrewe
    - tcbegley
